# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hello, Awesome World!
author:
  name: Jihye Ha
  email: jihye.ha.03@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Awesome place to share knowledge and expertise in BigData/Statistics/AI/Dev.
baseurl: "/blog-with-me" # the subpath of your site, e.g. /blog
url: "https://jihye-ha.github.io" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: false # set to true to show excerpts on the homepage


# gems:
#   - jekyll-paginate
# markdown: kramdown
# kramdown:
#   input: GFM
# excerpt_separator: "<!-- more -->"
# sass:
#   style: compressed
#   sass_dir: _scss    
# paginate: 5
# paginate_path: '/blog/page:num'
# permalink: pretty
# version: 1.0.0

# Build settings
theme: jekyll-theme-minimal

minima:
  social_links: 
    github: jihye-ha
    linkedin: jihye-ha
  date_format: "%b %-d, %Y"


plugins:
  - jekyll-feed
  # - jekyll-include-cache

include:
  - pages
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
  - headers/about.markdown
  - headers/bigdata.markdown
  - headers/statistics.markdown
  - headers/ai.markdown
  - headers/dev.markdown

category_title:
  bigdata: Big Data
  statistics: Statistics
  ai: AI
  dev: Development
